name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential git python3-dev zip zlib1g-dev libncurses5-dev \
            libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev \
            libsqlite3-dev sqlite3 bzip2 libbz2-dev libmql-dev \
            openjdk-17-jdk-headless
          pip3 install --user --upgrade Cython==0.29.33 buildozer

      - name: Build APK with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Lệnh này sẽ tự động chạy và đồng ý mọi yêu cầu từ Buildozer
          yes | buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "True"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
          
